### ISSUE TITLE
Add a helper script for updating the sha sums?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/dagster-feedstock#14]
When a new pack of releases come, the tick bot will only update one sha. Is there a convention for adding helper scripts in a way that future migrations won't mess with them? I'm imagining a pretty short script to be run by a maintainer that:
- reads the `meta.yml`
- finds all the name pairs
- downloads all the new tarballs
- gets their shas
- replaces them in `meta.yml`

**Comment by xhochy** [comment]
I would actually hope that we could extend the bot https://github.com/regro/cf-scripts to cater for this instead of having a script for each of the complicated feedstocks.

**Comment by bollwyvl** [comment]
Yeah, I get lost every time I try to touch that codebase... But I can take
a look...

**Comment by bollwyvl** [comment]
It looks like the bot did this correctly on #19!
