### ISSUE TITLE
support for dagster-cloud

### ISSUE THREAD

**Issue by geoHeil** [conda-forge/dagster-feedstock#353]
### Comment:

how to move the dagster-cloud pip package over to conda?

is there any automation to ease the process to fill in https://github.com/conda-forge/dagster-feedstock/blob/main/recipe/meta.yaml?

**Comment by bollwyvl** [comment]
This, and its daughter `dagster-libs-feedstock`, are already very complex feedstocks (even by conda-forge standards), and at present all quite manual, as the upstream dependency data is all in `setup.py` files which are... complex to reason about (usually manual diff). However, it's a diff against _one_ repo at two tags.

`dagster-cloud` (and its novel `daster-` dependencies) would bring in two _additional_ repos, and has `[extras]` that are probably important to users of those packages. I would recommend, if this is important, to start a new feedstock (potentially with multiple outputs) that ship this independent chain of packages.

As for automation, _starting_ is easy:

```bash
conda install grayskull
git clone https://github.com/conda-forge/staged-recipes
cd staged-recipes/recipes
grayskull pypi dagster-cloud
grayskull pypi dagster-cloud-cli
```

Make a PR, handle requests, off to the races.

Once a feedstock, it will get bot updates, and these can be further simplified with a `conda-forge.yml`

```yaml
bot:
  inspection: update-all
```

But _when_ that breaks, _maintaining_ it would be another, semi-weekly task for which _I_ am not super interested in signing up at this time.

**Comment by geoHeil** [comment]
understood - thanks for sharing

**Comment by geoHeil** [comment]
starting to prepare something here https://github.com/conda-forge/staged-recipes/pull/26708
