### ISSUE TITLE
why is dagster_gcp/dagster_pandas pulled in outdated version - do you observe the same?

### ISSUE THREAD

**Issue by geoHeil** [conda-forge/dagster-feedstock#374]
### Comment:

Hi,

I am facing https://github.com/conda-forge/dagster-cloud-feedstock/issues/4 we had a fruitful discussion https://github.com/conda-forge/dagster-feedstock/issues/356 to get these packages set up.

Do you observe / had observed similar issues? 

Do you have any idea how to fix it?

**Comment by bollwyvl** [comment]
Sorry, I don't really have any insight on how to improve the setup. Again, at the level of complexity and weirdness of the upstreams, and that it can sometimes take this and `dagster-libs` a few days to get right after a release (again, see upstreams), I don't think the automerge magic is likely to work in the general case.

**Comment by geoHeil** [comment]
thx
